[2021-05-28 19:52:44,185] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Covid19_UAE_DAG.installing_packages 2021-05-27T19:52:27.334684+00:00 [queued]>
[2021-05-28 19:52:44,220] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Covid19_UAE_DAG.installing_packages 2021-05-27T19:52:27.334684+00:00 [queued]>
[2021-05-28 19:52:44,221] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-28 19:52:44,222] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-28 19:52:44,223] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-28 19:52:44,258] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): installing_packages> on 2021-05-27T19:52:27.334684+00:00
[2021-05-28 19:52:44,281] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Covid19_UAE_DAG', 'installing_packages', '2021-05-27T19:52:27.334684+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/uae_covid19_dag.py', '--cfg-path', '/tmp/tmpho9lkeaz', '--error-file', '/tmp/tmp_csqru_y']
[2021-05-28 19:52:44,270] {standard_task_runner.py:52} INFO - Started process 48 to run task
[2021-05-28 19:52:44,283] {standard_task_runner.py:77} INFO - Job 16: Subtask installing_packages
[2021-05-28 19:52:44,347] {logging_mixin.py:104} INFO - Running <TaskInstance: Covid19_UAE_DAG.installing_packages 2021-05-27T19:52:27.334684+00:00 [running]> on host 897404cfb482
[2021-05-28 19:52:44,402] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Covid19_UAE_DAG
AIRFLOW_CTX_TASK_ID=installing_packages
AIRFLOW_CTX_EXECUTION_DATE=2021-05-27T19:52:27.334684+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-27T19:52:27.334684+00:00
[2021-05-28 19:52:44,403] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-28 19:52:44,404] {bash.py:158} INFO - Running command: pip install sklearn matplotlib
[2021-05-28 19:52:44,417] {bash.py:169} INFO - Output:
[2021-05-28 19:52:45,418] {bash.py:173} INFO - WARNING: The directory '/home/airflow/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[2021-05-28 19:52:46,168] {bash.py:173} INFO - Collecting sklearn
[2021-05-28 19:52:47,143] {bash.py:173} INFO -   Downloading sklearn-0.0.tar.gz (1.1 kB)
[2021-05-28 19:52:50,189] {bash.py:173} INFO - Collecting matplotlib
[2021-05-28 19:52:50,339] {bash.py:173} INFO -   Downloading matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
[2021-05-28 19:52:53,928] {bash.py:173} INFO - Collecting scikit-learn
[2021-05-28 19:52:54,004] {bash.py:173} INFO -   Downloading scikit_learn-0.24.2-cp36-cp36m-manylinux2010_x86_64.whl (22.2 MB)
[2021-05-28 19:52:56,842] {bash.py:173} INFO - Collecting cycler>=0.10
[2021-05-28 19:52:56,916] {bash.py:173} INFO -   Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
[2021-05-28 19:52:57,263] {bash.py:173} INFO - Collecting kiwisolver>=1.0.1
[2021-05-28 19:52:57,348] {bash.py:173} INFO -   Downloading kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
[2021-05-28 19:52:57,861] {bash.py:173} INFO - Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (2.4.7)
[2021-05-28 19:53:00,036] {bash.py:173} INFO - Collecting pillow>=6.2.0
[2021-05-28 19:53:00,171] {bash.py:173} INFO -   Downloading Pillow-8.2.0-cp36-cp36m-manylinux1_x86_64.whl (3.0 MB)
[2021-05-28 19:53:01,004] {bash.py:173} INFO - Requirement already satisfied: numpy>=1.15 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (1.19.5)
[2021-05-28 19:53:01,014] {bash.py:173} INFO - Requirement already satisfied: python-dateutil>=2.1 in /home/airflow/.local/lib/python3.6/site-packages (from matplotlib) (2.8.1)
[2021-05-28 19:53:01,461] {bash.py:173} INFO - Collecting joblib>=0.11
[2021-05-28 19:53:01,539] {bash.py:173} INFO -   Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
[2021-05-28 19:53:02,290] {bash.py:173} INFO - Collecting threadpoolctl>=2.0.0
[2021-05-28 19:53:02,456] {bash.py:173} INFO -   Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
[2021-05-28 19:53:03,808] {bash.py:173} INFO - Collecting scipy>=0.19.1
[2021-05-28 19:53:03,878] {bash.py:173} INFO -   Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
[2021-05-28 19:53:09,769] {bash.py:173} INFO - Requirement already satisfied: six in /home/airflow/.local/lib/python3.6/site-packages (from cycler>=0.10->matplotlib) (1.15.0)
[2021-05-28 19:53:09,773] {bash.py:173} INFO - Building wheels for collected packages: sklearn
[2021-05-28 19:53:09,775] {bash.py:173} INFO -   Building wheel for sklearn (setup.py): started
[2021-05-28 19:53:11,525] {bash.py:173} INFO -   Building wheel for sklearn (setup.py): finished with status 'done'
[2021-05-28 19:53:11,526] {bash.py:173} INFO -   Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1316 sha256=99fd10aa61d3320e88fdfebb8ff7e21f18b1b4481f29c69b3fe92dba2b0fa01f
[2021-05-28 19:53:11,527] {bash.py:173} INFO -   Stored in directory: /tmp/pip-ephem-wheel-cache-dh70d4xz/wheels/23/9d/42/5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c
[2021-05-28 19:53:11,528] {bash.py:173} INFO - Successfully built sklearn
[2021-05-28 19:53:23,589] {bash.py:173} INFO - Installing collected packages: joblib, threadpoolctl, scipy, scikit-learn, sklearn, cycler, kiwisolver, pillow, matplotlib
[2021-05-28 19:53:28,989] {bash.py:173} INFO - ERROR: Exception:
[2021-05-28 19:53:28,989] {bash.py:173} INFO - Traceback (most recent call last):
[2021-05-28 19:53:28,990] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
[2021-05-28 19:53:28,991] {bash.py:173} INFO -     status = self.run(options, args)
[2021-05-28 19:53:28,992] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
[2021-05-28 19:53:28,993] {bash.py:173} INFO -     return func(self, options, args)
[2021-05-28 19:53:28,994] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 406, in run
[2021-05-28 19:53:28,994] {bash.py:173} INFO -     pycompile=options.compile,
[2021-05-28 19:53:28,995] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
[2021-05-28 19:53:28,995] {bash.py:173} INFO -     pycompile=pycompile,
[2021-05-28 19:53:28,995] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 822, in install
[2021-05-28 19:53:28,996] {bash.py:173} INFO -     requested=self.user_supplied,
[2021-05-28 19:53:28,996] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/install/wheel.py", line 860, in install_wheel
[2021-05-28 19:53:28,997] {bash.py:173} INFO -     requested=requested,
[2021-05-28 19:53:28,997] {bash.py:173} INFO -   File "/usr/local/lib/python3.6/site-packages/pip/_internal/operations/install/wheel.py", line 734, in _install_wheel
[2021-05-28 19:53:28,998] {bash.py:173} INFO -     assert os.path.exists(pyc_path)
[2021-05-28 19:53:28,998] {bash.py:173} INFO - AssertionError
[2021-05-28 19:53:29,618] {bash.py:173} INFO - WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
[2021-05-28 19:53:29,622] {bash.py:173} INFO - You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
[2021-05-28 19:53:30,068] {bash.py:177} INFO - Command exited with return code 2
[2021-05-28 19:53:30,176] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-28 19:53:30,201] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=Covid19_UAE_DAG, task_id=installing_packages, execution_date=20210527T195227, start_date=20210528T195244, end_date=20210528T195330
[2021-05-28 19:53:30,365] {local_task_job.py:146} INFO - Task exited with return code 1
